services:
  medialyze:
    image: ghcr.io/frederikemmer/medialyze:latest
    container_name: medialyze
    hostname: medialyze
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      # change to your timezone, e.g. "Europe/Berlin" or "America/New_York"
      TZ: ${TZ:-UTC}
      CONFIG_PATH: /config
      MEDIA_ROOT: /media
      MEDIALYZE_TRANSCODE_OUTPUT_ROOT: /transcode-output
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-compute,video,utility}
      PUID: ${PUID:-}
      PGID: ${PGID:-}
    volumes:
      - ${CONFIG_HOST_DIR:-./config}:/config
      - ${MEDIA_HOST_DIR:-./media}:/media:ro
      - ${TRANSCODE_OUTPUT_HOST_DIR:-./Transcode_Output}:/transcode-output:rw

      # additional media mounts are managed as:
      # /PATH/TO/MEDIA1:/media/MEDIA1:ro
      # /PATH/TO/MEDIA2:/media/MEDIA2:ro
