services:
  medialyze:
    image: ghcr.io/frederikemmer/medialyze:latest
    container_name: medialyze
    hostname: medialyze
    ports:
      - 8080:8080
    environment:
      # change to your timezone, e.g. "Europe/Berlin" or "America/New_York"
      TZ: UTC
    volumes:
      - ./config:/config
      - PATH/TO/MEDIA0:/media/MEDIA0:ro

      # additional media mounts are managed as:
      # /PATH/TO/MEDIA1:/media/MEDIA1:ro
      # /PATH/TO/MEDIA2:/media/MEDIA2:ro
