services:
  medialyze:
    image: ghcr.io/frederikemmer/medialyze:latest
    container_name: medialyze
    hostname: medialyze
    ports:
      - "${HOST_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      # change to your timezone, e.g. "Europe/Berlin" or "America/New_York"
      TZ: ${TZ:-UTC}
    volumes:
      - ${CONFIG_HOST_DIR:-./config}:/config
      - ${MEDIA_HOST_DIR:-./media}:/media:ro
      
      # if you want to manage multiple mounts, use this instead and delete the above media mount:
      # /PATH/TO/MEDIA1:/media/MEDIA1:ro
      # /PATH/TO/MEDIA2:/media/MEDIA2:ro
