services:
  medialyze:
    image: ghcr.io/frederikemmer/medialyze:latest
    container_name: medialyze
    ports:
      - "${HOST_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      # change to your timezone, e.g. "Europe/Berlin" or "America/New_York"
      TZ: ${TZ:-UTC}
    volumes:
      - ${CONFIG_HOST_DIR:-./config}:/config
      # use .env or change "${MEDIA_HOST_DIR:-./media}" to the path of your media directory
      - ${MEDIA_HOST_DIR:-./media}:/media:ro
      
      # additional media mounts, if needed. Extend this pattern if needed:
      # /PATH/TO/MEDIA1:/media/MEDIA1:ro
